### ISSUE TITLE
Login to Google will not allow My Snippets to work

### ISSUE THREAD

**Issue by bryanamundson** [pscustomdev/sss#18]
When you login to Google and click on My Snippets, it takes you back to the login page.  Only when you login to Github will it allow you to run My Snippets.

**Comment by kgividen** [comment]
Fixed

**Comment by bryanamundson** [comment]
Clicking My Snippets no longer takes me to the login page, but it doesn't show any of my snippets.  When I login using Github, it lists 2 snippets in My Snippets.

**Comment by kgividen** [comment]
Right.  Those are two different logins not the same login so they would have different snippets.  You'd need to create snippets under Google for them to show up.  So it's working like it's supposed to.

**Comment by bryanamundson** [comment]
As a user I assume that different ways to login are for my convenience and that either way I do it, I am still the same person and should have the same resources.  If we have implemented this the same way Cloud 9 or other SAAS sites work (that you have different profiles depending on how you login) then I accept this solution.

**Comment by kgividen** [comment]
Yea they are treated as two separate logins right now and there's no way to link them.  Which is how I think most sites work.  If we want some way to link them we can look into that and would have to use email address or something.
