### ISSUE TITLE
Create a new box for Highest Ranked Snippets

### ISSUE THREAD

**Issue by kgividen** [pscustomdev/sss#74]

**Comment by bryanamundson** [comment]
Store a score on the snippet calculated as follows:

10 x number of 5 star ratings
5 x number of 4 star ratings
2 x number of 3 star ratings
0 x number of 2 star ratings
0 x number of 1 star ratings

This calculation would be done in a nightly process.

**Comment by kgividen** [comment]
We need to create a new SnippetRanking collection
We need to create a new dbGetSnippetRankings in the dao
When a rating is updated it needs to update the new SnippetRanking Collection with the ID and the rank.

**Comment by kgividen** [comment]
DAO stuff is done.  Need to still need to calculate and add the snippet ranking when a snippet is rated.  The test is on the branch but still needs to be implemented in the api.js

**Comment by kgividen** [comment]
This is finished.
