### ISSUE TITLE
Create a box list of people who have the most high ranked snippets

### ISSUE THREAD

**Issue by kgividen** [pscustomdev/sss#75]
List of people who have submitted the "best" snippets.  "Highest Rated Submitter"
Best rated snippet
Most snippets
Most download snippets.

**Comment by bryanamundson** [comment]
Store a score on the user record calculated as:

10 x number of 5 star ratings
5 x number of 4 star ratings
2 x number of 3 star ratings
0 x number of 2 star ratings
0 x number of 1 star ratings

This calculation would be done in a night process.

**Comment by kgividen** [comment]
First two items are done.  Rankings are on the user and added/subtracted when a ratings is added/updated.

Now we need to expose it on the UI

**Comment by kgividen** [comment]
This is checked in.
